version: 1
accounts:
  - name: client1
    coins: ["500token", "10000000000stake"]
  - name: client2
    coins: ["500token", "10000000000stake"]
  - name: client3
    coins: ["500token"]
  - name: client4
    coins: ["500token"]
  - name: client5
    coins: ["500token"]
  - name: client6
    coins: ["500token"]
  - name: client7
    coins: ["500token"]
  - name: client8
    coins: ["500token"]
  - name: client9
    coins: ["500token"]
  - name: client10
    coins: ["500token"]
  - name: client11
    coins: ["500token"]
  - name: client12
    coins: ["500token"]
  - name: client13
    coins: ["500token"]
  - name: client14
    coins: ["500token"]
  - name: client15
    coins: ["500token"]
  - name: client16
    coins: ["500token"]
  - name: client17
    coins: ["500token"]
  - name: client18
    coins: ["500token"]
  - name: client19
    coins: ["500token"]
  - name: client20
    coins: ["500token"]
validators:
  - name: client1
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: client2
  coins: ["5token", "100000stake"]
